#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"

is_webhook() {
  echo "$1" | grep -E '^http[s]?://'
}

get_discord_root() {
  if [[ -z $(is_webhook "$1") ]]; then
    verify_app_name "$1"
    APP="$1"
    echo "$DOKKU_ROOT/$APP"
  else
    echo "$DOKKU_ROOT"
  fi
}

get_webhook() {
  if [[ -n $1 && -n $2 ]]; then
    echo "$2"
  else
    echo "$1"
  fi
}

case "$1" in
  discord:set)
    DISCORD_ROOT=$(get_discord_root "$2")
    WEBHOOK=$(get_webhook "$2" "$3")
    [[ -z $WEBHOOK ]] && echo "Please specify at least a webhook URL" && exit 1
    [[ -z $(is_webhook "$WEBHOOK") ]] && echo "Webhook has to be an URL" && exit 1
    echo "$WEBHOOK" > "$DISCORD_ROOT/DISCORD_URL"
    ;;

  discord:clear)
    DISCORD_ROOT=$(get_discord_root "$2")
    rm "$DISCORD_ROOT/DISCORD_URL"
    ;;

  discord:get)
    DISCORD_ROOT=$(get_discord_root "$2")
    cat "$DISCORD_ROOT/DISCORD_URL"
    ;;

  help)
    HELP=$(cat<<EOF
    discord:set [app] <webhook_url>, Set Discord WebHook URL
    discord:clear [app], Clears Discord WebHook URL
    discord:get [app], Display Discord WebHook URL
EOF
)
    if [[ -n $DOKKU_API_VERSION ]]; then
      echo "$HELP"
    else
      cat && echo "$HELP"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac
